### ISSUE TITLE
Firefox can't detect documentation character encoding because it is served as text/html

### ISSUE THREAD

**Issue by wallrj** [twisted-infra/t-web#1]
When I view eg
 * https://twistedmatrix.com/documents/current/core/howto/basics.html

Firefox web console complains "The character encoding of the HTML document was not declared."

And unicode characters like " — " appear garbled.

Probably because the documents are served with "Content-Type: text/html" .

Should be served using the application/xhtml+xml MIME type according to:
 * https://en.wikipedia.org/wiki/XHTML#XML_declaration

**Comment by adiroiban** [comment]
Moved to https://github.com/twisted-infra/braid/issues/117
